### ISSUE TITLE
SHARK Stable Release Tracker (12/2023)

### ISSUE THREAD

**Issue by monorimet** [nod-ai/SHARK#2005]
Adding a list of TODOs:

- [ ] MultiControlNet
   - [ ]  resize input image(s) to desired output size
   - [ ] verify correctness of pipeline structure -- are we using the right unet weights?
   - [ ] enable "controlnet t2i adaptation", i.e. t2i with controlnet adapters ( ? )
- [ ] SDXL
   - [ ] LoRAs
   - [ ] vulkan issues with SDXL-1.0 1024x1024
   - [ ] controlnet

- [ ] fix nod logo
- [ ] fix UX regressions caused by gradio version update

**Comment by monorimet** [comment]
> can we have sdxl turbo too added?

Done. https://github.com/nod-ai/SHARK/releases/tag/20231205.1064

**Comment by radudiaconu0** [comment]
<img width="856" alt="image" src="https://github.com/nod-ai/SHARK/assets/52667211/02ae576f-ff87-422a-9955-f91ede6275bc">
i get this on rx 7900xtx on default settings on sd xl turbo

**Comment by radudiaconu0** [comment]
@monorimet

**Comment by MattisBergmann** [comment]
When switching to sdxl-turbo, it disables the positive prompt, leaving only the negative one. Instead, I have to write the prompt while in sdxl-base mode, then switch to turbo.

**Comment by MattisBergmann** [comment]
The sdxl-turbo model works mostly fine for me, but trying to run sdxl-base results in
`SystemExit: SharkifyStableDiffusionModel.get_unet_sdxl.<locals>.UnetModel.forward() missing 2 required positional arguments: 'time_ids' and 'guidance_scale'`
OS: EndeavourOS/Arch Linux
GPU: RX 7900 XT (using amdvlk as mesa/vulkan-radeon is broken)
Settings: 512x512 50 steps

**Comment by monorimet** [comment]
> When switching to sdxl-turbo, it disables the positive prompt, leaving only the negative one. Instead, I have to write the prompt while in sdxl-base mode, then switch to turbo.

There's something goofy about the inputs/guidance scale for the SDXL implementation. This is actually intended behavior as a quick'n'dirty workaround but it's not a long term solution. I'll add a task for it.
